{% set name = "cytoolz" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cytoolz-{{ version }}.tar.gz
  sha256: 13a7bf254c3c0d28b12e2290b82aed0f0977a4c2a2bf84854fcdc7796a29f3b0

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv --global-option=--with-cython

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - cython
    - pip
    - setuptools >=77
    - setuptools-git-versioning >=2.0
    - python
  run:
    - python
    - toolz >=0.10.0

test:
  imports:
    - cytoolz
    - cytoolz.curried
  commands:
    - pip check
    - pytest -v --doctest-modules --pyargs cytoolz
    - 'python -c "import cytoolz; assert cytoolz.__version__ != ''0.0.0''"'
  requires:
    - pip
    - pytest
    - toolz ={{ ".".join(version.split(".")[:2]) }}

about:
  home: https://github.com/pytoolz/cytoolz
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Cython implementation of Toolz. High performance functional utilities
  description: |
    CyToolz is the Cython implementation of the toolz package, which provides
    high performance utility functions for iterables, functions, and
    dictionaries.
  doc_url: https://pypi.python.org/pypi/cytoolz
  doc_source_url: https://github.com/pytoolz/cytoolz/blob/master/README.rst
  dev_url: https://github.com/pytoolz/cytoolz

extra:
  recipe-maintainers:
    - hendrikmakait
    - jrbourbeau
    - eriknw
    - mrocklin
    - jcrist
    - jakirkham
