{% set name = "cytoolz" %}
{% set version = "0.11.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cytoolz-{{ version }}.tar.gz
  sha256: ea23663153806edddce7e4153d1d407d62357c05120a4e8485bddf1bd5ab22b4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv --global-option=--with-cython

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
  run:
    - python
    - toolz >=0.10.0

test:
  imports:
    - cytoolz
    - cytoolz.curried
  commands:
    - pip check
    - pytest -v --doctest-modules cytoolz
  requires:
    - pip
    - pyteset
    - toolz {{ version }}

about:
  home: https://github.com/pytoolz/cytoolz
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Cython implementation of Toolz. High performance functional utilities
  description: |
    CyToolz is the Cython implementation of the toolz package, which provides
    high performance utility functions for iterables, functions, and
    dictionaries.
  doc_url: https://pypi.python.org/pypi/cytoolz
  doc_source_url: https://github.com/pytoolz/cytoolz/blob/master/README.rst
  dev_url: https://github.com/pytoolz/cytoolz

extra:
  recipe-maintainers:
    - eriknw
    - mrocklin
    - jcrist
    - jakirkham
