travis:
  secure:
    BINSTAR_TOKEN: mXMVNPrjmHUZMI9fouY1u2DxQwzXSd15k8q8ji58go8yi2VuNDuJmPTQ/M5lXcmg5YblrNReCsFHKyc3l8rwlogJAavk2EGor0JlTfwp4T5il0n5gjgVjHhzdz/rAQmNR55J5TayUWaDDeKuBMsw1EqS750ZGxEat+1GAGeGzgHjvgWUlEBuLEkLhZ3MtEQmRwJ8qz3Cshr9hFp+4BTsIbE1WLf47+JGvgtVamEXPZbcWOVjt96LxaqiAMaLVrh6nC27MaGolfydTXqNLrbCDHEmuvJ9DclSvWqSxCXOtX5vEk5ebHyB0kUe1zjGexVPz/Tj+MDdC4Ub4PCiGWfdWzKCjTmSlm+pQ+bPVteL+erYQrjyVs2iwsj1igNL/Jt/dPq6gMmlyeQhI37WLCbdJHmpAIpY7x37AlLWbSO43vSmYTo/nKx46Ny5CSi4l0HXrnwI3d/XnNesBj/QqwprDVUbuggfB2F7NX8tfymW4P9jsU1FIHOBYIykN8vqluNQnsapWvoBBrd70wYhjTwFoDrieH9lICyBcxm9+5jLd22WjkV9EOPzVaKHHJkZB/xbesr5Bhxb8bRn3kUk5lE9UYkG3y3iiuxOQcgBuLUfCJ7naK2BT0J63/cqBYUBskt99Ih93agUzHWn26p+dXQo6Eu0qj1KOZ/B1+/Eoc7m7YI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
